apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: dev-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: 142081895333.dkr.ecr.eu-central-1.amazonaws.com/admin-service
        ports:
        - containerPort: 4005
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: dev-environment
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005

